### ISSUE TITLE
Needs a branch

### ISSUE THREAD

**Issue by Arjunkuls** [pbprimeplay/JS-QUIZ-school#1]

**Comment by Arjunkuls** [comment]
You should go to settings and add a master branch so people can view the output

**Comment by pbprimeplay** [comment]
hey ok fine but don't copy

**Comment by pbprimeplay** [comment]
how are you supposed to do that

**Comment by Arjunkuls** [comment]
Go to settings

**Comment by Arjunkuls** [comment]
scroll down

**Comment by pbprimeplay** [comment]
then

**Comment by Arjunkuls** [comment]
you will see something to do with branch

**Comment by Arjunkuls** [comment]
click on drop down

**Comment by Arjunkuls** [comment]
select master, hit save and let it refresh, it will give you link which should activate within 5 minutes

**Comment by pbprimeplay** [comment]
yes option called branches

**Comment by pbprimeplay** [comment]
there is no dropdown

**Comment by Arjunkuls** [comment]
what do you see?

**Comment by Arjunkuls** [comment]
send an image if you need to

**Comment by pbprimeplay** [comment]
i clicked on dropdown and there is - main and Files

**Comment by pbprimeplay** [comment]
just tell on discord
